
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 462968
	#The name of the modpack
	modpackName = "Beneath The Trees"
	#The version of the modpack
	modpackVersion = "0.0.25"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

