
[endrem]
	#Enable/Disable usage of Ender Eyes
	enable_ender_eyes = false
	#Enable/Disable the End Castle
	enable_end_castle = true
	#Enable/Disable the End Gate
	enable_end_gate = true
	#Distance in chunks between End Castles
	castle_distance = 500
	#Distance in chunks between End Gates
	end_gate_distance = 500
	#Size of the End Gates
	end_gate_size = 30
	#Sets the Behavior of the Custom Eyes (0 for disabled, 1 to locate Castle and 2 to locate End Gate)
	eye_behavior = 2
	#Sets the Behavior of the Custom Map (0 for disabled, 1 to locate Castle and 2 to locate End Gate)
	map_behavior = 1

