
#Client configuration settings
[client]
	#Generate classic chairs.
	generateClassicChairs = true
	#Generate shield chairs.
	generateShieldChairs = true
	#Generate short stools.
	generateShortStools = true
	#Generate tall stools.
	generateTallStools = true
	#Generate benches.
	generateBenches = true
	#Integrate with Biomes O Plenty.
	bopIntegration = true
	#Integrate with Oh The Biomes You Go.
	bygIntegration = true
	#Integrate with Immersive Engineering.
	ieIntegration = true

