
#Dynamic Lights Settings
[Settings]

	[Settings.Misc]
		"Cloud Height [Raw, Default 196]" = 196
		"Chunk Fade In Quality (OFF, FAST, FANCY)" = "FANCY"
		"Render Fog" = true
		#Allowed Values: WINDOWED, BORDERLESS, FULLSCREEN
		"Use Borderless Fullscreen" = "FULLSCREEN"

	[Settings."FPS Counter"]
		"Display FPS Counter (OFF, SIMPLE, ADVANCED)" = "OFF"
		"FPS Counter Distance" = 12

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = true
		"(TileEntity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(TileEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096

	[Settings.Zoom]
		"Lower Zoom Sensitivity" = true
		"Zoom Scrolling Enabled" = true
		"Zoom Transition Mode (OFF, LINEAR, SMOOTH)" = "SMOOTH"
		"Zoom Transition Mode (TOGGLE, HOLD, PERSISTENT)" = "HOLD"
		"Cinematic Camera Mode (OFF, VANILLA, MULTIPLIED)" = "OFF"
		"Zoom Overlay?" = true

