
#Project: Vibrant Journeys settings
[Settings]

	#World Gen Settings
	[Settings."World Gen"]
		seaOats = true
		cattails = true
		barkMushrooms = true
		cobwebs = true
		bushes = true
		glowcap = true
		netherNettles = true
		shortGrass = true
		beachGrass = true
		fallenTrees = true
		#Seagrass in lakes
		moreSeagrass = true
		#Denser river grass
		moreGrassInRivers = true

		[Settings."World Gen".Groundcover]
			rocks = true
			twigs = true
			fallenLeaves = true
			bones = true
			charredBones = true
			iceChunks = true
			pinecones = true
			seashells = true
			# % chance of groundcover placement
			#Range: 0 ~ 100
			groundcoverChance = 100
			#Groundcover Biome Blacklist, example: ["minecraft:plains", "minecraft:beach"]
			groundcoverBlacklist = []

	[Settings."Mob Settings"]

		[Settings."Mob Settings"."Mob Toggles"]
			"Enable Flies" = true
			"Enable Fireflies" = true
			"Enable Starfish" = true
			"Enable Clams" = true
			"Enable Snails" = true
			"Enable Slugs" = true
			"Enable Small Spiders" = true
			"Enable Frogs" = true

		[Settings."Mob Settings"."Misc Mob Settings"]
			"Mute Flies" = false

		[Settings."Mob Settings"."Vanilla Mob Settings"]
			#Tropical fish in jungles
			jungleTropicalFish = true
			#Bats spawn outside at night
			nightBats = true

	#Biome Settings
	[Settings.Biomes]
		overgrownSpires = true
		verdantSands = true

