#
###Version, do not change!##
#Range: > 0
Version = 7

#Small Ships Config:
[Ships]
	#
	#----Cog Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.25
	#Range: 0.0 ~ 2.0
	CogSpeedFactor = 1.25
	#
	#----Brigg Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.28
	#Range: 0.0 ~ 2.0
	BriggSpeedFactor = 1.28
	#
	#----Ship Zoom.----
	#	(takes effect after restart)
	#	default: 0.2
	#Range: 1.0 ~ 20.0
	ShipZoom = 6.0
	#
	#----Cog Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.1
	#Range: 0.0 ~ 1.0
	CogTurnFactor = 0.1
	#
	#----Row Boat Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.0
	#Range: 0.0 ~ 2.0
	DrakkarSpeedFactor = 1.0
	#
	#----Drakkar Ice Break Speed.----
	#	(takes effect after restart)
	#	higher values = slower break speed
	#	default: 2.0
	#Range: 0.0 ~ 100.0
	DrakkarIceBreakSpeed = 2.0
	#
	#----Should Ships Make WaterMobs flee?----
	#	(takes effect after restart)
	#	default: true
	WaterMobFlee = true
	#
	#----Galley Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.5
	#Range: 0.0 ~ 1.0
	GalleyTurnFactor = 0.5
	#
	#----Should the player enter ships in third person?----
	#	(takes effect after restart)
	#	default: true
	EnterThirdPerson = true
	#
	#----Row Boat Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.8
	#Range: 0.0 ~ 1.0
	DrakkarTurnFactor = 0.8
	#
	#----War Galley Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.15
	#Range: 0.0 ~ 2.0
	WarGalleySpeedFactor = 1.15
	#
	#----Should the Ships make waving animation?----
	#	(takes effect after restart)
	#	default: true
	MakeWaveAnimation = true
	#
	#----Brigg Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.2
	#Range: 0.0 ~ 1.0
	BriggTurnFactor = 0.2
	#
	#----Galley Speed Factor.----
	#	(takes effect after restart)
	#	default: 1.3
	#Range: 0.0 ~ 2.0
	GalleySpeedFactor = 1.3
	#
	#----Should Ships Make Swimming sounds?----
	#	(takes effect after restart)
	#	default: true
	PlaySwimmSound = true
	#
	#----War Galley Turn Factor.----
	#	(takes effect after restart)
	#	default: 0.4
	#Range: 0.0 ~ 1.0
	WarGalleyTurnFactor = 0.4

